# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Leland Wright
tagline:          Professional Amateur
description:      "Just a geek with his toys."
url:              https://www.lelandwright.com
baseurl:          /
                  # the optional subpath of your site, e.g. "/my-jekyll-site/"
                  # This will apply to all pages in your Jekyll site.

author:
  name:           Leland Wright
  url:            https://www.lelandwright.com

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            2.0.1

github:
  repo:             https://github.com/wright2006/wright2006.github.io
